### ISSUE TITLE
Read command list from actual console

### ISSUE THREAD

**Issue by zajca** [mojoLyon/fish-sf#11]
Hi,
nice plugin but predefined commands are not really useful since lot of things is missing specially from other bundles. I'm not really familiar with fish and it's plugins but command can be read like this:
```
app/console --no-ansi | sed "1,/Available commands/d" | awk '/^  ?[a-z]+/ { print $1 }'
```
I'm not sure if fish can read completions from command.

**Comment by mojoLyon** [comment]
Not sure it will be possible. I will try it.
Thanks for the command line.

**Comment by mojoLyon** [comment]
Added completion for custom command : #12
